name: customer360-churn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - numpy
  - python-dotenv
  - pandas
  - geopandas
  - contextily
  - tqdm
  - kaggle
  - matplotlib
  - seaborn
  - streamlit
  - shap
  - scikit-learn
  - scipy
  - xgboost
  - openpyxl
  - pip
  - pip:
    - neo4j
    - neo4j-viz==1.1.0
    - playwright
    - pyspark==3.5.1
